name: Java CI with Allure Report (manual push to gh-pages)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: mvn clean test

      - name: Install Allure CLI via Linuxbrew
        shell: bash
        run: |
          # Check if brew is already installed
          if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            git clone https://github.com/Homebrew/brew /home/linuxbrew/.linuxbrew/Homebrew
            mkdir -p /home/linuxbrew/.linuxbrew/bin
            ln -s /home/linuxbrew/.linuxbrew/Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            echo "eval \"$($(brew --prefix)/bin/brew shellenv)\"" >> $GITHUB_ENV
          else
            echo "Homebrew already installed"
            echo "eval \"$($(brew --prefix)/bin/brew shellenv)\"" >> $GITHUB_ENV
          fi

          source $GITHUB_ENV
          brew install allure

      - name: Generate Allure report
        shell: bash
        run: |
          source $GITHUB_ENV
          allure generate target/allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report